### PR TITLE
add sendMaintenanceMessage/cancelMaintenanceMessage

### PR DESCRIPTION
**Pull request by AbdelHedhili**

### CODE REVIEW

**Review by jamal-khey — APPROVED** [review]
Code and tests Ok

**Comment by AbdelHedhili** [comment]
> i found an issue , i don't know if it count as a bug.
> 
> if we send 2 messages and try to cancel them , we can only cancel the last one.

indeed i can correct that

**Review by jamal-khey — APPROVED** [review]
test and code OK

**Review by flomillot — APPROVED** [review]
An other PR will follow to finish the feature

**Pull request merged**
